/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Barrio;
import Modelo.Comuna;
import Modelo.Incidente;
import Modelo.TipoIngresoInsidente;
import Modelo.TipoInscidente;
import Modelo.Usuario;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Form_reporte_barrio extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIPrincipal
     */
    public Form_reporte_barrio(Controlador cont) {
        initComponents();
        this.controlador = cont;
        cargarSelect();

    }
    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void cargarSelect() {
        combo_barrio_reporte.removeAllItems();
        combo_barrio_reporte.addItem("Seleccione");
        for (int i = 0; i < getControlador().getListabarrios().size(); i++) {
            combo_barrio_reporte.addItem(getControlador().getListabarrios().get(i).getBar_nombre());
        }
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo_barrio_reporte = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaIncidente = new javax.swing.JTable();
        jBListarIncidentes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jPasswordField1.setText("jPasswordField1");

        setIconifiable(true);
        setResizable(true);
        setTitle("Menu");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setText("Reporte Por Barrios");

        jLabel4.setText("Seleccione El barrio");

        combo_barrio_reporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_barrio_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_barrio_reporteActionPerformed(evt);
            }
        });

        tableListaIncidente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barrio", "Codigo", "Descripcion", "Fecha", "Usuario", "Tipo Incidente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableListaIncidente);

        jBListarIncidentes.setText("Cargar Incidentes");
        jBListarIncidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarIncidentesActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(127, 127, 127)
                .addComponent(combo_barrio_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jBListarIncidentes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(combo_barrio_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBListarIncidentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("Iniciar_Resgis");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_barrio_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_barrio_reporteActionPerformed

//        for (int i = 0; i < getControlador().getLstbarrio().size(); i++) {
//            combo_barrio_reporte.addItem(getControlador().getLstbarrio().get(i).getBar_nombre());
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_barrio_reporteActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:

//        combo_tipoingreso_incidente.removeAllItems();
//        combo_tipoingreso_incidente.removeAllItems();  
//        
//         
//        for(int i=0; i<getControlador().getListatipoingresoincidente().size(); i++){
//            combo_tipoingreso_incidente.addItem(getControlador().getListatipoingresoincidente().get(i).getTii_descripcion());
//            System.out.println("getControlador().getListabarrios().get(i).getInc_descripcionIncidente() = " + getControlador().getListabarrios().get(i).getBar_nombre());
//        }
//         combo_tipo_incidente.removeAllItems();
//         for(int i=0; i<getControlador().getListaTipoInscidentes().size(); i++){
//            combo_tipoingreso_incidente.addItem(getControlador().getListaTipoInscidentes().get(i).getTipinc_descripcion());
//            System.out.println("getControlador().getListabarrios().get(i).getInc_descripcionIncidente() = " + getControlador().getListabarrios().get(i).getBar_nombre());
//        }

    }//GEN-LAST:event_formInternalFrameOpened

    private void jBListarIncidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarIncidentesActionPerformed
        // TODO add your handling code here:

        int barrio = combo_barrio_reporte.getSelectedIndex();

        if (barrio != 0) {

            Barrio codigobarrio = controlador.buscarBarrio(combo_barrio_reporte.getSelectedItem().toString());
            getControlador().cargarIncidentesPorBarrio(codigobarrio.getBar_codigo());
            DefaultTableModel lstIncidente = (DefaultTableModel) tableListaIncidente.getModel();
            if (!getControlador().getListaInci().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Se tienen " + getControlador().getListaInci().size() + " Incidentes Registrados en el Barrio:  " + codigobarrio.getBar_nombre());
                tableListaIncidente.removeAll();

                int rowCount = lstIncidente.getRowCount();
                for (int i = 0; i < rowCount; i++) {
                    lstIncidente.removeRow(i);
                }
                for (int i = 0; i < getControlador().getListaInci().size(); i++) {
                    lstIncidente.addRow(new Object[]{getControlador().getListaInci().get(i).getBarrio().getBar_nombre(), getControlador().getListaInci().get(i).getInc_codigoIncidente(), getControlador().getListaInci().get(i).getInc_descripcionIncidente(), getControlador().getListaInci().get(i).getInc_fechaIncidente(), getControlador().getListaInci().get(i).getUsuario().getTelefono(), getControlador().getListaInci().get(i).getTipo_incidente().getTipinc_descripcion()});
                }
            } else {

                JOptionPane.showMessageDialog(null, "No tiene Se Tienen Incidentes en el Barrio:  " + codigobarrio.getBar_nombre());
                int rowCount = lstIncidente.getRowCount();
                for (int i = 0; i < rowCount; i++) {
                    lstIncidente.removeRow(i);
                }
                if (lstIncidente.getRowCount() > 0) {
                    lstIncidente.removeRow(tableListaIncidente.getSelectedRow());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Un Barrio");
        }

    }//GEN-LAST:event_jBListarIncidentesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_barrio_reporte;
    private javax.swing.JButton jBListarIncidentes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tableListaIncidente;
    // End of variables declaration//GEN-END:variables
}
