/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Barrio;
import Modelo.Comuna;
import Modelo.Incidente;
import Modelo.TipoIngresoInsidente;
import Modelo.TipoInscidente;
import Modelo.Usuario;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Form_Ingresar_Incidente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIPrincipal
     */
    public Form_Ingresar_Incidente(Controlador cont) {
        initComponents();
        this.controlador=cont;
        cargarSelect();
        
    }
    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void cargarSelect() {
        combo_tipoingreso_incidente.removeAllItems();
        combo_tipo_incidente.removeAllItems();
        combo_comuna.removeAllItems();
        combo_comuna.addItem("Seleccione");
        for (int i = 0; i < getControlador().getListatipoingresoincidente().size(); i++) {
            combo_tipoingreso_incidente.addItem(getControlador().getListatipoingresoincidente().get(i).getTii_descripcion());
        }
        for (int i = 0; i < getControlador().getListaTipoInscidentes().size(); i++) {
            combo_tipo_incidente.addItem(getControlador().getListaTipoInscidentes().get(i).getTipinc_descripcion());
        }
        for (int i = 0; i < getControlador().getListacomunas().size(); i++) {
            combo_comuna.addItem(getControlador().getListacomunas().get(i).getCom_nombre());
        }

    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        labelnombre = new javax.swing.JLabel();
        labeldireccion = new javax.swing.JLabel();
        labelcontraseña = new javax.swing.JLabel();
        labelcontraseña1 = new javax.swing.JLabel();
        btn_guardar_incidente = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        combo_tipo_incidente = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion_incidente = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo_tipoingreso_incidente = new javax.swing.JComboBox();
        combo_comuna = new javax.swing.JComboBox();
        combo_barrio = new javax.swing.JComboBox();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jPasswordField1.setText("jPasswordField1");

        setIconifiable(true);
        setResizable(true);
        setTitle("Menu");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        labelnombre.setText("Descripcion Incidente:");

        labeldireccion.setText("Tipo Incidente:");

        labelcontraseña.setText("Comuna:");

        labelcontraseña1.setText("Barrio:");

        btn_guardar_incidente.setText("Guardar");
        btn_guardar_incidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_incidenteActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        combo_tipo_incidente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_tipo_incidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipo_incidenteActionPerformed(evt);
            }
        });

        txt_descripcion_incidente.setColumns(20);
        txt_descripcion_incidente.setRows(5);
        jScrollPane1.setViewportView(txt_descripcion_incidente);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setText("INGRESE INFORMACION DEL INCIDENTE");

        jLabel4.setText("Tipo ingreso de Incidente:");

        combo_tipoingreso_incidente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_tipoingreso_incidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoingreso_incidenteActionPerformed(evt);
            }
        });

        combo_comuna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_comuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_comunaActionPerformed(evt);
            }
        });

        combo_barrio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_barrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_barrioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel3)
                .addGap(0, 136, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btn_guardar_incidente)
                        .addGap(58, 58, 58)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelnombre)
                            .addComponent(jLabel4)
                            .addComponent(labelcontraseña1)
                            .addComponent(labelcontraseña)
                            .addComponent(labeldireccion))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_tipo_incidente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_tipoingreso_incidente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(combo_barrio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_tipoingreso_incidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(combo_tipo_incidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelnombre)
                        .addGap(89, 89, 89)
                        .addComponent(labeldireccion)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelcontraseña)
                    .addComponent(combo_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcontraseña1)
                    .addComponent(combo_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar_incidente)
                    .addComponent(btn_cancelar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Iniciar_Resgis");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardar_incidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_incidenteActionPerformed

        TipoIngresoInsidente codigotipoingreso = controlador.buscarTipoIngresoIncidente(combo_tipoingreso_incidente.getSelectedItem().toString());
        String descripcionincidente = txt_descripcion_incidente.getText();

        TipoInscidente codigotipoincidente = controlador.buscarTipoIncidente(combo_tipo_incidente.getSelectedItem().toString());
        if (!txt_descripcion_incidente.getText().equals("")) {
            if (!combo_comuna.getSelectedItem().toString().equals("Seleccione") && !combo_barrio.getSelectedItem().toString().equals("Seleccione")) {
                Comuna codigocomuna = controlador.buscarComuna(combo_comuna.getSelectedItem().toString());
                Barrio codigobarrio = controlador.buscarBarrio(combo_barrio.getSelectedItem().toString());

                Incidente incidente = new Incidente(controlador.getListaIncidentes().size()+1,descripcionincidente,new Date(),codigotipoincidente,codigotipoingreso,new Usuario("Ciudadano"),codigocomuna,codigobarrio);
                controlador.guardarIncidente(incidente);
                JOptionPane.showMessageDialog(null, "Se ha registrado exitosamente el Incidente");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una Comuna o el barrio");

            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe Llenar el campo de descripcion");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn_guardar_incidenteActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void combo_tipoingreso_incidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoingreso_incidenteActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tipoingreso_incidenteActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:

//        combo_tipoingreso_incidente.removeAllItems();
//        combo_tipoingreso_incidente.removeAllItems();  
//        
//         
//        for(int i=0; i<getControlador().getListatipoingresoincidente().size(); i++){
//            combo_tipoingreso_incidente.addItem(getControlador().getListatipoingresoincidente().get(i).getTii_descripcion());
//            System.out.println("getControlador().getListabarrios().get(i).getInc_descripcionIncidente() = " + getControlador().getListabarrios().get(i).getBar_nombre());
//        }
//         combo_tipo_incidente.removeAllItems();
//         for(int i=0; i<getControlador().getListaTipoInscidentes().size(); i++){
//            combo_tipoingreso_incidente.addItem(getControlador().getListaTipoInscidentes().get(i).getTipinc_descripcion());
//            System.out.println("getControlador().getListabarrios().get(i).getInc_descripcionIncidente() = " + getControlador().getListabarrios().get(i).getBar_nombre());
//        }

    }//GEN-LAST:event_formInternalFrameOpened

    private void combo_tipo_incidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipo_incidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tipo_incidenteActionPerformed

    private void combo_comunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_comunaActionPerformed
        // TODO add your handling code here:

        int comuna = combo_comuna.getSelectedIndex();
        getControlador().cargarBarrio(comuna);
        combo_barrio.removeAllItems();
        for (int i = 0; i < getControlador().getLstbarrio().size(); i++) {
            combo_barrio.addItem(getControlador().getLstbarrio().get(i).getBar_nombre());
        }
    }//GEN-LAST:event_combo_comunaActionPerformed

    private void combo_barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_barrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_barrioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar_incidente;
    private javax.swing.JComboBox combo_barrio;
    private javax.swing.JComboBox combo_comuna;
    private javax.swing.JComboBox combo_tipo_incidente;
    private javax.swing.JComboBox combo_tipoingreso_incidente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcontraseña;
    private javax.swing.JLabel labelcontraseña1;
    private javax.swing.JLabel labeldireccion;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JTextArea txt_descripcion_incidente;
    // End of variables declaration//GEN-END:variables
}
