/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Waldo
 */
public class MDIAinicio extends javax.swing.JFrame {

    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * Creates new form MDIAinicio
     */
    public MDIAinicio() {
        initComponents();
        controlador = new Controlador();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        fondo = new javax.swing.JPanel();
        panel_login = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        optmenu_Reportes_Comuna = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        optmenu_inscribete = new javax.swing.JMenuItem();
        optmenu_ingresousuregistrado = new javax.swing.JMenuItem();
        optmenu_ciudadano = new javax.swing.JMenuItem();
        optmenu_incidente = new javax.swing.JMenu();
        optmenu_ingresar_incidente = new javax.swing.JMenuItem();
        optmenu_actualizar_incidente = new javax.swing.JMenuItem();
        optmenu_Reportes = new javax.swing.JMenu();
        optmenu_ingresar_incidente1 = new javax.swing.JMenuItem();
        optmenu_actualizar_incidente1 = new javax.swing.JMenuItem();
        optmenu_reporte_tipo_incidente_y_comuna_barrio = new javax.swing.JMenuItem();
        optmenu_reporte_doble = new javax.swing.JMenuItem();
        optmenu_actualizar_incidente4 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel5.setText("jLabel5");

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_login.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        panel_login.setVisible(true);

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña: ");

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });

        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("SRI INGRESAR");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login.getContentPane());
        panel_login.getContentPane().setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btn_ingresar))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_ingresar)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        titulo1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        titulo1.setForeground(new java.awt.Color(153, 0, 153));
        titulo1.setText("SISTEMA DE REGISTRO DE INCIDENTES");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 508, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(23, 23, 23))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap())))
        );

        desktopPane.add(fondo);
        fondo.setBounds(0, 10, 910, 490);

        optmenu_Reportes_Comuna.setBackground(new java.awt.Color(224, 182, 116));
        optmenu_Reportes_Comuna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        optmenu_Reportes_Comuna.setMnemonic('f');
        optmenu_Reportes_Comuna.setText("Inicio");
        optmenu_Reportes_Comuna.setToolTipText("Inicio");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        optmenu_Reportes_Comuna.add(exitMenuItem);

        optmenu_inscribete.setMnemonic('o');
        optmenu_inscribete.setText("Inscribete");
        optmenu_inscribete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_inscribeteActionPerformed(evt);
            }
        });
        optmenu_Reportes_Comuna.add(optmenu_inscribete);

        optmenu_ingresousuregistrado.setText("Ingreso Usuario Registrado");
        optmenu_ingresousuregistrado.setEnabled(false);
        optmenu_ingresousuregistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_ingresousuregistradoActionPerformed(evt);
            }
        });
        optmenu_Reportes_Comuna.add(optmenu_ingresousuregistrado);

        optmenu_ciudadano.setText("Ingreso Ciudadano");
        optmenu_ciudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_ciudadanoActionPerformed(evt);
            }
        });
        optmenu_Reportes_Comuna.add(optmenu_ciudadano);

        optmenu_incidente.setMnemonic('f');
        optmenu_incidente.setText("Gestionar Incidentes");
        optmenu_incidente.setEnabled(false);

        optmenu_ingresar_incidente.setMnemonic('o');
        optmenu_ingresar_incidente.setText("Ingresar Incidente");
        optmenu_ingresar_incidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_ingresar_incidenteActionPerformed(evt);
            }
        });
        optmenu_incidente.add(optmenu_ingresar_incidente);

        optmenu_actualizar_incidente.setMnemonic('o');
        optmenu_actualizar_incidente.setText("Actualizar Incidente");
        optmenu_actualizar_incidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_actualizar_incidenteActionPerformed(evt);
            }
        });
        optmenu_incidente.add(optmenu_actualizar_incidente);

        optmenu_Reportes_Comuna.add(optmenu_incidente);

        optmenu_Reportes.setMnemonic('f');
        optmenu_Reportes.setText("Reportes");
        optmenu_Reportes.setEnabled(false);

        optmenu_ingresar_incidente1.setMnemonic('o');
        optmenu_ingresar_incidente1.setText("Incidentes por Barrio");
        optmenu_ingresar_incidente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_ingresar_incidente1ActionPerformed(evt);
            }
        });
        optmenu_Reportes.add(optmenu_ingresar_incidente1);

        optmenu_actualizar_incidente1.setMnemonic('o');
        optmenu_actualizar_incidente1.setText("Incidentes por Comuna");
        optmenu_actualizar_incidente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_actualizar_incidente1ActionPerformed(evt);
            }
        });
        optmenu_Reportes.add(optmenu_actualizar_incidente1);

        optmenu_reporte_tipo_incidente_y_comuna_barrio.setMnemonic('o');
        optmenu_reporte_tipo_incidente_y_comuna_barrio.setText("Incidentes por Tipo Incidente");
        optmenu_reporte_tipo_incidente_y_comuna_barrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_reporte_tipo_incidente_y_comuna_barrioActionPerformed(evt);
            }
        });
        optmenu_Reportes.add(optmenu_reporte_tipo_incidente_y_comuna_barrio);

        optmenu_reporte_doble.setMnemonic('o');
        optmenu_reporte_doble.setText("Incidentes por Tipo y Comuna");
        optmenu_reporte_doble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_reporte_dobleActionPerformed(evt);
            }
        });
        optmenu_Reportes.add(optmenu_reporte_doble);

        optmenu_actualizar_incidente4.setMnemonic('o');
        optmenu_actualizar_incidente4.setText("Incidentes por Tipo, Comuna y Barrio");
        optmenu_actualizar_incidente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_actualizar_incidente4ActionPerformed(evt);
            }
        });
        optmenu_Reportes.add(optmenu_actualizar_incidente4);

        optmenu_Reportes_Comuna.add(optmenu_Reportes);

        menuBar.add(optmenu_Reportes_Comuna);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed

        // TODO add your handling code here:
        if (getControlador().validarUsuario(txt_usuario.getText(), txt_contraseña.getText())) {

            panel_login.dispose();
            optmenu_incidente.setEnabled(true);
            optmenu_inscribete.setEnabled(false);
            optmenu_ciudadano.setEnabled(false);
            optmenu_ingresousuregistrado.setEnabled(false);
            optmenu_Reportes.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Bienvenido");

        } else {
            if (txt_usuario.getText().equals("") || txt_contraseña.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe diligencias todos los campos");
            } else {
                JOptionPane.showMessageDialog(this, "El usuario ingresado no existe");
            }
        }

    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void optmenu_inscribeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_inscribeteActionPerformed

        panel_login.dispose();
        optmenu_ingresousuregistrado.setEnabled(true);
        Form_Inscribirse prin = new Form_Inscribirse(controlador);
        fondo.add(prin);
        prin.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_optmenu_inscribeteActionPerformed

    private void optmenu_actualizar_incidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_actualizar_incidenteActionPerformed
        // TODO add your handling code here:

        if (!getControlador().getListaIncidentes().isEmpty()) {

        } else {
            JOptionPane.showMessageDialog(null, "No tiene Se Tienen Incidentes");
        }
        Form_Actualizar_Incidente actualizarIncidente = new Form_Actualizar_Incidente(controlador);
        fondo.add(actualizarIncidente);
        // actualizarIncidente.setControlador(controlador);
        actualizarIncidente.toFront();
        actualizarIncidente.show();
    }//GEN-LAST:event_optmenu_actualizar_incidenteActionPerformed

    private void optmenu_ingresar_incidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_ingresar_incidenteActionPerformed
        panel_login.dispose();
        Form_Ingresar_Incidente fii = new Form_Ingresar_Incidente(controlador);
        //fii.setControlador(controlador);
        fondo.add(fii);
        fii.show();
    }//GEN-LAST:event_optmenu_ingresar_incidenteActionPerformed

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaActionPerformed

    private void optmenu_ingresousuregistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_ingresousuregistradoActionPerformed
        // TODO add your handling code here:
        panel_login.dispose();
        Form_Ingresar fin = new Form_Ingresar(controlador);
        fondo.add(fin);
        fin.show();
    }//GEN-LAST:event_optmenu_ingresousuregistradoActionPerformed

    private void optmenu_ciudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_ciudadanoActionPerformed

        optmenu_incidente.setEnabled(true);
        panel_login.dispose();
        optmenu_ingresousuregistrado.setEnabled(false);
        optmenu_inscribete.setEnabled(false);
        optmenu_actualizar_incidente.setEnabled(false);
        optmenu_Reportes.setEnabled(true);
        optmenu_ciudadano.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_optmenu_ciudadanoActionPerformed

    private void optmenu_ingresar_incidente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_ingresar_incidente1ActionPerformed
        // TODO add your handling code here:
        panel_login.dispose();
        Form_reporte_barrio fr = new Form_reporte_barrio(controlador);
        fondo.add(fr);
        fr.show();
    }//GEN-LAST:event_optmenu_ingresar_incidente1ActionPerformed

    private void optmenu_actualizar_incidente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_actualizar_incidente1ActionPerformed
        Form_reporte_comuna fr = new Form_reporte_comuna(controlador);
        fondo.add(fr);
        fr.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_optmenu_actualizar_incidente1ActionPerformed

    private void optmenu_reporte_tipo_incidente_y_comuna_barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_reporte_tipo_incidente_y_comuna_barrioActionPerformed
        Form_reporte_Tipo_incidente fr = new Form_reporte_Tipo_incidente(controlador);
        fondo.add(fr);
        fr.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_optmenu_reporte_tipo_incidente_y_comuna_barrioActionPerformed

    private void optmenu_reporte_dobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_reporte_dobleActionPerformed
        Form_reporte_comuna_y_tipo fr = new Form_reporte_comuna_y_tipo(controlador);
        fondo.add(fr);
        fr.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_optmenu_reporte_dobleActionPerformed

    private void optmenu_actualizar_incidente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_actualizar_incidente4ActionPerformed
        Form_reporte_comuna_tipo_y_barrio fr = new Form_reporte_comuna_tipo_y_barrio(controlador);
        fondo.add(fr);
        fr.show();

// TODO add your handling code here:
    }//GEN-LAST:event_optmenu_actualizar_incidente4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIAinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIAinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIAinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIAinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIAinicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu optmenu_Reportes;
    private javax.swing.JMenu optmenu_Reportes_Comuna;
    private javax.swing.JMenuItem optmenu_actualizar_incidente;
    private javax.swing.JMenuItem optmenu_actualizar_incidente1;
    private javax.swing.JMenuItem optmenu_actualizar_incidente4;
    private javax.swing.JMenuItem optmenu_ciudadano;
    private javax.swing.JMenu optmenu_incidente;
    private javax.swing.JMenuItem optmenu_ingresar_incidente;
    private javax.swing.JMenuItem optmenu_ingresar_incidente1;
    private javax.swing.JMenuItem optmenu_ingresousuregistrado;
    private javax.swing.JMenuItem optmenu_inscribete;
    private javax.swing.JMenuItem optmenu_reporte_doble;
    private javax.swing.JMenuItem optmenu_reporte_tipo_incidente_y_comuna_barrio;
    private javax.swing.JInternalFrame panel_login;
    private javax.swing.JLabel titulo1;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

}
