/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Waldo
 */
public class MDIAinicio extends javax.swing.JFrame {

    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * Creates new form MDIAinicio
     */
    public MDIAinicio() {
        initComponents();
        controlador = new Controlador();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        fondo = new javax.swing.JPanel();
        panel_login = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        optmenu_salir = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        optmenu_inscribete = new javax.swing.JMenuItem();
        optmenu_ingresousuregistrado = new javax.swing.JMenuItem();
        optmenu_ciudadano = new javax.swing.JMenuItem();
        optmenu_incidente = new javax.swing.JMenu();
        optmenu_ingresar_incidente = new javax.swing.JMenuItem();
        optmenu_actualizar_incidente = new javax.swing.JMenuItem();
        optmenu_reportes = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel5.setText("jLabel5");

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_login.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        panel_login.setVisible(true);

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña: ");

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });

        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("SRI INGRESAR");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login.getContentPane());
        panel_login.getContentPane().setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btn_ingresar))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_ingresar)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        titulo1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        titulo1.setForeground(new java.awt.Color(153, 0, 153));
        titulo1.setText("SISTEMA DE REGISTRO DE INCIDENTES");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Waldo\\Desktop\\logo.png")); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(23, 23, 23))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        desktopPane.add(fondo);
        fondo.setBounds(-20, 0, 900, 480);

        optmenu_salir.setMnemonic('f');
        optmenu_salir.setText("Inicio");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        optmenu_salir.add(exitMenuItem);

        optmenu_inscribete.setMnemonic('o');
        optmenu_inscribete.setText("Inscribete");
        optmenu_inscribete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_inscribeteActionPerformed(evt);
            }
        });
        optmenu_salir.add(optmenu_inscribete);

        optmenu_ingresousuregistrado.setText("Ingreso Usuario Registrado");
        optmenu_ingresousuregistrado.setEnabled(false);
        optmenu_ingresousuregistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_ingresousuregistradoActionPerformed(evt);
            }
        });
        optmenu_salir.add(optmenu_ingresousuregistrado);

        optmenu_ciudadano.setText("Ingreso Ciudadano");
        optmenu_ciudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_ciudadanoActionPerformed(evt);
            }
        });
        optmenu_salir.add(optmenu_ciudadano);

        optmenu_incidente.setMnemonic('f');
        optmenu_incidente.setText("Gestionar Incidentes");
        optmenu_incidente.setEnabled(false);

        optmenu_ingresar_incidente.setMnemonic('o');
        optmenu_ingresar_incidente.setText("Ingresar Incidente");
        optmenu_ingresar_incidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_ingresar_incidenteActionPerformed(evt);
            }
        });
        optmenu_incidente.add(optmenu_ingresar_incidente);

        optmenu_actualizar_incidente.setMnemonic('o');
        optmenu_actualizar_incidente.setText("Actualizar Incidente");
        optmenu_actualizar_incidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_actualizar_incidenteActionPerformed(evt);
            }
        });
        optmenu_incidente.add(optmenu_actualizar_incidente);

        optmenu_reportes.setText("Reportes");
        optmenu_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmenu_reportesActionPerformed(evt);
            }
        });
        optmenu_incidente.add(optmenu_reportes);

        optmenu_salir.add(optmenu_incidente);

        menuBar.add(optmenu_salir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed

        // TODO add your handling code here:
        if (getControlador().validarUsuario(txt_usuario.getText(), txt_contraseña.getText())) {

            panel_login.dispose();
            optmenu_incidente.setEnabled(true);
            optmenu_inscribete.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Bienvenido");

        } else {
            if (txt_usuario.getText().equals("") || txt_contraseña.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe diligencias todos los campos");
            } else {
                JOptionPane.showMessageDialog(this, "El usuario ingresado no existe");
            }
        }

    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void optmenu_inscribeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_inscribeteActionPerformed

        panel_login.dispose();
        optmenu_ingresousuregistrado.setEnabled(true);
        Form_Inscribirse prin = new Form_Inscribirse();
        fondo.add(prin);
        prin.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_optmenu_inscribeteActionPerformed

    private void optmenu_actualizar_incidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_actualizar_incidenteActionPerformed
        // TODO add your handling code here:

        if (!getControlador().getListaIncidentes().isEmpty()) {

        } else {
            JOptionPane.showMessageDialog(null, "No tiene Se Tienen Incidentes");
        }
        Form_Actualizar_Incidente actualizarIncidente = new Form_Actualizar_Incidente();
        fondo.add(actualizarIncidente);
        actualizarIncidente.toFront();
        actualizarIncidente.show();
    }//GEN-LAST:event_optmenu_actualizar_incidenteActionPerformed

    private void optmenu_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_reportesActionPerformed
        // TODO add your handling code here:
         panel_login.dispose();
        Form_Reportes fr = new Form_Reportes();
        fondo.add(fr);
        fr.show();
    }//GEN-LAST:event_optmenu_reportesActionPerformed

    private void optmenu_ingresar_incidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_ingresar_incidenteActionPerformed
        panel_login.dispose();
        Form_Ingresar_Incidente fii = new Form_Ingresar_Incidente();
        fondo.add(fii);
        fii.show();
    }//GEN-LAST:event_optmenu_ingresar_incidenteActionPerformed

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaActionPerformed

    private void optmenu_ingresousuregistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_ingresousuregistradoActionPerformed
        // TODO add your handling code here:
        panel_login.dispose();
        Form_Ingresar fin = new Form_Ingresar();
        fondo.add(fin);
        fin.show();
    }//GEN-LAST:event_optmenu_ingresousuregistradoActionPerformed

    private void optmenu_ciudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmenu_ciudadanoActionPerformed

        optmenu_incidente.setEnabled(true);
        panel_login.dispose();
        optmenu_ingresousuregistrado.setEnabled(false);
        optmenu_inscribete.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_optmenu_ciudadanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIAinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIAinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIAinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIAinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIAinicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem optmenu_actualizar_incidente;
    private javax.swing.JMenuItem optmenu_ciudadano;
    private javax.swing.JMenu optmenu_incidente;
    private javax.swing.JMenuItem optmenu_ingresar_incidente;
    private javax.swing.JMenuItem optmenu_ingresousuregistrado;
    private javax.swing.JMenuItem optmenu_inscribete;
    private javax.swing.JMenuItem optmenu_reportes;
    private javax.swing.JMenu optmenu_salir;
    private javax.swing.JInternalFrame panel_login;
    private javax.swing.JLabel titulo1;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

}
